version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:12.6
commands:
  restore_npm:
    steps:
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "package.json" }}
  save_npm:
    steps:
      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
jobs:
  build:
    executor: default
    working_directory: ~/unplugged-hp
    steps:
      - checkout
      - restore_npm
      - run: yarn install
      - run: yarn generate
      - persist_to_workspace:
          root: ~/unplugged-hp
          paths:
            - dist
      - save_npm
  stage:
      executor: default
      working_directory: ~/unplugged-hp
      steps:
          - attach_workspace:
              at: ~/unplugged-hp
          - run:
              name: stage to Firebase
              command: node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  deploy:
    jobs:
      - build
      - stage:
          requires:
            - build
          filters:
              branches:
                only:
                  - develop
                  - master
