version: 2
executors:
  defualt:
    docker:
      - image: circleci/node:12.6
commands:
  restore_npm:
    steps:
      - restore_cache:
          - yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
  save_npm:
    steps:
      - save_cache:
        paths:
          - node_modules
        keys:
          - yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

jobs:
  build:
    executor:
      name: default
    working_directory: ~/unplugged-hp
    steps:
      - checkout
      - restore_npm
      - run: yarn install
      - run: yarn generate
      - persist_to_workspace:
        root: ~/unplugged-hp
        paths:
          - dist
      - save_npm
  stage:
    executor:
      name: default
    working_directory: ~/unplugged-hp
    steps:
      - attach_workspace:
        at: ~/unplugged-hp
      - run:
        name: stage to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - build:
      - stage:
        requires:
          - build
        filters:
          branches:
            - develop
            - master
