name: generate

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Get yarn cache
        id: yarn-cache
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
          yarn cache dir

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v1
        with:
          path: "node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        run: |
          yarn cache dir
          yarn

      - name: generate
        run: |
          yarn run md
          yarn run generate
